version: '3.8'

services:
  web:
    build: .
    ports:
      - "90:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: security2db
      MYSQL_DATABASE: dbmain
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: security2db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

volumes:
  db_data:
